version: '3.8'

services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: telemetry_backend
    restart: always
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - DOC_TOKEN=public
      - DIRECTUS_URL=${DIRECTUS_URL:-http://91.99.137.101:8056/}
      - DIRECTUS_TOKEN=${DIRECTUS_TOKEN:-UuazE-Np-VrpGxmqe-bEpysiTSjV8_YR}
    networks:
      - telemetry_network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: telemetry_frontend
    restart: always
    ports:
      - "8090:80"
    depends_on:
      - backend
    networks:
      - telemetry_network

networks:
  telemetry_network:
    driver: bridge
