version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telemetry_app
    restart: always
    ports:
      - "8090:8090"
    environment:
      - NODE_ENV=production
      - PORT=8090
      - DOC_TOKEN=public
      - DIRECTUS_URL=${DIRECTUS_URL}
      - DIRECTUS_TOKEN=${DIRECTUS_TOKEN}
    networks:
      - telemetry_network

networks:
  telemetry_network:
    driver: bridge
